"""
Code change reviewer for Existential Therapist bot.
Tracks file hashes and generates changelogs on startup.
"""

import os
import json
import hashlib
import re
import random
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from datetime import datetime

# Files to track for changes
TRACKED_FILES = [
    "src/telegram_bot.py",
    "src/therapist_bot.py", 
    "src/i18n.py",
    "src/lang_utils.py",
]

# Existing commands that should NOT be mentioned as "new" in changelogs
EXISTING_COMMANDS = [
    "start", "help", "lang", "switchlang", "reset", "assoc", "analyze",
    "meta", "silence", "void", "meaning", "meaning_is", "meaning_gone",
    "meaning_where", "look", "feedback", "stats", "askprob",
    "recover", "saveall", "dumpall"
]


# Predefined comments for changelog (existential therapist style)
# These are used at the TOP of the changelog, not generated by LLM
CHANGELOG_COMMENTS_RU = [
    "Бот обновился — как и всё живое.",
    "Мы улучшили то, что можно улучшить.",
    "Новые возможности для исследования себя.",
    "Обновление: теперь работает ещё лучше.",
    "Время перемен — бот растёт вместе с нами.",
    "Исправлено то, что мешало погружению.",
    "Код эволюционирует — смысл остаётся.",
    "Обновление: шаг к более глубокому диалогу.",
    "Техника служит терапии — мы её подправили.",
    "Всё течёт, всё меняется. Включая этого бота.",
]


CHANGELOG_COMMENTS_EN = [
    "The bot has evolved — as all living things do.",
    "We've improved what could be improved.",
    "New possibilities for self-exploration.",
    "Update: now works even better.",
    "Time for change — the bot grows with us.",
    "Fixed what was getting in the way of immersion.",
    "Code evolves — meaning remains.",
    "Update: a step toward deeper dialogue.",
    "Technology serves therapy — we've tuned it.",
    "Everything flows, everything changes. Including this bot.",
]




def calculate_file_hash(file_path: Path) -> str:
    """Calculate SHA256 hash of file contents."""
    try:
        with open(file_path, 'rb') as f:
            return hashlib.sha256(f.read()).hexdigest()[:16]
    except Exception:
        return ""


def load_stored_hashes(data_dir: Path) -> Dict[str, str]:
    """Load previously stored file hashes."""
    hash_file = data_dir / "code_hashes.json"
    if hash_file.exists():
        try:
            with open(hash_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def save_hashes(data_dir: Path, hashes: Dict[str, str]) -> None:
    """Save current file hashes."""
    hash_file = data_dir / "code_hashes.json"
    try:
        data_dir.mkdir(parents=True, exist_ok=True)
        with open(hash_file, 'w', encoding='utf-8') as f:
            json.dump(hashes, f, ensure_ascii=False, indent=2)
    except Exception as e:
        print(f"Failed to save hashes: {e}")


def get_changed_files(project_root: Path, stored_hashes: Dict[str, str]) -> List[Tuple[str, str, str]]:
    """
    Compare current files with stored hashes.
    Returns list of (filename, old_hash, new_hash) for changed files.
    """
    changed = []
    for rel_path in TRACKED_FILES:
        file_path = project_root / rel_path
        if file_path.exists():
            current_hash = calculate_file_hash(file_path)
            old_hash = stored_hashes.get(rel_path, "")
            if current_hash != old_hash:
                changed.append((rel_path, old_hash, current_hash))
    return changed


def extract_commands_from_code(content: str) -> List[str]:
    """Extract command names from code content."""
    commands = []
    patterns = [
        r'Command\(["\'](/\w+)["\']',
        r'@self\.dp\.message\(Command\(["\'](\w+)["\']',
        r'async def cmd_(\w+)\(',
    ]
    for pattern in patterns:
        matches = re.findall(pattern, content)
        for match in matches:
            cmd = match if match.startswith('/') else f"/{match}"
            if cmd not in commands:
                commands.append(cmd)
    return commands


def analyze_code_changes(project_root: Path, changed_files: List[Tuple[str, str, str]]) -> Dict[str, List[str]]:
    """Analyze what actually changed in the code."""
    result = {
        "new_commands": [],
        "all_commands": [],
        "has_changes": False,
        "changed_files_count": len(changed_files)
    }
    
    for rel_path, old_hash, new_hash in changed_files:
        file_path = project_root / rel_path
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            commands = extract_commands_from_code(content)
            if commands:
                result["all_commands"].extend(commands)
            
            result["has_changes"] = True
        except Exception:
            result["has_changes"] = True
    
    # Remove duplicates
    result["all_commands"] = list(set(result["all_commands"]))
    return result


def get_changelog_comment(num_changes: int, lang: str = "ru") -> str:
    """Get ONE predefined comment for changelog (existential therapist style).
    
    Comment is placed at the TOP of the changelog, not generated by LLM.
    """
    if lang == "ru":
        return random.choice(CHANGELOG_COMMENTS_RU)
    else:
        return random.choice(CHANGELOG_COMMENTS_EN)



def generate_changelog_with_llm(therapist_bot, changed_files: List[Tuple[str, str, str]], project_root: Path, lang: str = "ru") -> str:
    """
    Use LLM to generate a human-readable changelog based on file changes.
    """
    if not changed_files:
        return ""
    
    num_changes = len(changed_files)
    
    # Start with predefined comment from templates (at the TOP)
    # This is NOT generated by LLM - taken from predefined list
    header_comment = get_changelog_comment(num_changes, lang)

    
    # Generate content for each changed file
    diff_sections = []

    for rel_path, old_hash, new_hash in changed_files:
        file_path = project_root / rel_path
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            diff_sections.append(f"File: {rel_path}\n{content[:5000]}")
        except Exception as e:
            diff_sections.append(f"File: {rel_path}\n[Error: {e}]")
    
    diff_content = "\n\n".join(diff_sections)
    
    if lang == "ru":
        prompt = f"""Ты — product manager экзистенциального терапевт-бота. 
Пиши changelog для пользователей в тёплом, человечном стиле.

АНАЛИЗИРУЙ КОД и выяви что изменилось для ПОЛЬЗОВАТЕЛЯ:
- Новые команды терапии (функции cmd_*) — как они помогают в работе с собой
- Улучшения существующих команд — что стало лучше в диалоге
- Исправленные баги — что чинили, чтобы не мешало разговору
- Новые возможности — как это поможет в исследовании себя

ПРАВИЛА:
1. Пиши ТОЛЬКО о реальных изменениях в коде ниже
2. НЕ придумывай команды или фичи которых нет
3. Пиши простым языком, как для друга, не для программиста
4. Используй тёплый, эмпатичный тон (в духе Ирвина Ялома)
5. Максимум 4-5 пунктов, только значимое
6. Формат: "- [Краткое название]: что изменилось и зачем это пользователю"
7. Без повторов в начале пунктов, каждый пункт должен быть уникальным
8. НЕ добавляй никаких заключительных фраз типа "Спасибо", "Благодарим", "С уважением"

Изменённые файлы:
{diff_content}

Напиши changelog на русском. Будь конкретным, но сохраняй тёплый, человечный тон."""
    else:
        prompt = f"""You are a product manager for an existential therapist bot.
Write a changelog for users in a warm, human style.

ANALYZE THE CODE and identify what changed for USERS:
- New therapy commands (cmd_* functions) — how they help with self-work
- Improvements to existing commands — what got better in the dialogue
- Fixed bugs — what was repaired to not interrupt the conversation
- New features — how this helps in self-exploration

RULES:
1. Write ONLY about REAL changes in the code below
2. DO NOT invent commands or features that don't exist
3. Write in plain language, like for a friend, not a programmer
4. Use warm, empathetic tone (in the spirit of Irvin Yalom)
5. Maximum 4-5 items, significant changes only
6. Format: "- [Brief name]: what changed and why it matters to users"
7. No repetitive patterns at the start, each item should be unique
8. DO NOT add any closing remarks like "Thanks", "Thank you", "Best regards"

Changed files:
{diff_content}

Write changelog in English. Be specific but keep a warm, human tone."""



    
    try:
        if therapist_bot and therapist_bot.client:
            response = therapist_bot.client.chat.completions.create(
                model=therapist_bot.model,
                messages=[
                    {"role": "system", "content": "Ты пишешь краткие notes к релизам. Не придумывай. Будь честным. НЕ используй markdown (звёздочки, жирный шрифт)." if lang == "ru" else "You write brief release notes. Don't hallucinate. Be honest. NO markdown formatting (no asterisks, no bold)."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.1,
                max_tokens=800
            )
            changelog = response.choices[0].message.content.strip()
            
            # Return with predefined comment at the TOP (not generated by LLM)
            if changelog and len(changelog) > 10 and "Internal" not in changelog:
                return f"{header_comment}\n\n{changelog}"
            else:
                fallback_text = 'Внутренние улучшения стабильности и надёжности.' if lang == 'ru' else 'Internal stability and reliability improvements.'
                return f"{header_comment}\n\n{changelog if changelog else fallback_text}"



    except Exception as e:
        print(f"LLM changelog generation failed: {e}")
    
    # Fallback: simple, friendly message
    if lang == "ru":
        return "Внутренние улучшения стабильности и надёжности."
    else:
        return "Internal stability and reliability improvements."



def generate_user_friendly_fallback(analysis: Dict, lang: str = "ru") -> str:
    """Generate a user-friendly changelog without technical details."""
    num_changes = analysis.get("changed_files_count", 1)
    
    # Predefined comment at the TOP (not generated by LLM)
    header_comment = get_changelog_comment(num_changes, lang)
    
    if lang == "ru":
        lines = [header_comment]
        
        if analysis["all_commands"]:
            for cmd in analysis["all_commands"][:5]:
                lines.append(f"- Доступна команда {cmd}")
        
        if len(lines) == 1:
            lines.append("- Улучшена стабильность и надёжность работы")

    else:
        lines = [header_comment]
        
        if analysis["all_commands"]:
            for cmd in analysis["all_commands"][:5]:
                lines.append(f"- Command {cmd} is available")
        
        if len(lines) == 1:
            lines.append("- Improved stability and reliability")


    
    return "\n".join(lines)



def check_and_generate_changelog(project_root: Path, therapist_bot, admin_id: int, lang: str = "ru", should_save_hashes: bool = True) -> Optional[str]:
    """
    Main entry point: check for changes and generate changelog.
    Returns changelog text if changes detected, None otherwise.
    
    Args:
        project_root: Path to project root
        therapist_bot: ExistentialTherapistBot instance for LLM calls
        admin_id: Admin user ID (for reference, not used in this function)
        lang: Language code (ru/en)
        should_save_hashes: If True, saves hashes after generating changelog. Set to False for testing.
    
    Note: Hashes should be saved by the caller AFTER sending notifications to prevent
    duplicate notifications on subsequent restarts.
    """
    try:
        data_dir = project_root / "data"
        
        stored_hashes = load_stored_hashes(data_dir)
        changed_files = get_changed_files(project_root, stored_hashes)
        
        if not changed_files:
            print(f"[CHANGELOG] No code changes detected, skipping notification")
            return None
        
        print(f"[CHANGELOG] Detected {len(changed_files)} changed file(s):")
        for rel_path, old_hash, new_hash in changed_files:
            print(f"  - {rel_path}: {old_hash} -> {new_hash}")
        
        # Generate changelog
        changelog = generate_changelog_with_llm(therapist_bot, changed_files, project_root, lang)
        
        # Update stored hashes only if requested
        # NOTE: This should be called by the caller AFTER notifications are sent successfully
        if should_save_hashes:
            current_hashes = {}
            for rel_path in TRACKED_FILES:
                file_path = project_root / rel_path
                if file_path.exists():
                    current_hashes[rel_path] = calculate_file_hash(file_path)
            
            save_hashes(data_dir, current_hashes)
            print(f"[CHANGELOG] Hashes saved to prevent duplicate notifications")
        
        return changelog
    except Exception as e:
        print(f"Error in check_and_generate_changelog: {e}")
        import traceback
        traceback.print_exc()
        return None



# Alias for backward compatibility with telegram_bot.py
save_current_hashes = save_hashes
